version: '3'
services:
  apache:
    build:
      context: ./apache
    container_name: he-apache
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - HE-network
    volumes:
      - ./app/:/var/www/app
  #Postgres
  postgres:
    image: postgres:11
    container_name: he-datamart
    restart: unless-stopped
    tty: true
    ports:
      - "54320:5432"
    volumes:
      - he-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "EsuezebiQuoh8"
      POSTGRES_DB: "he_datamart"
    networks:
      - HE-network
  # Pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: he-pgadmin
    ports:
      - "8081:8081"
    environment:
      PGADMIN_DEFAULT_EMAIL: "foo@bar.com"
      PGADMIN_DEFAULT_PASSWORD: "IopoonuN2ooli"
      PGADMIN_LISTEN_PORT: "8081"
    volumes:
    - he-db-data:/root/.pgadmin
    networks:
      - HE-network
  
#Docker Networks
networks:
  HE-network:
    driver: bridge
volumes:
  he-db-data: